/*
Fatture in Cloud API v2 - API Reference

Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.

API version: 2.0.23
Contact: info@fattureincloud.it
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package model

import (
	"encoding/json"
)

// CreateSupplierResponse struct for CreateSupplierResponse
type CreateSupplierResponse struct {
	Data *Supplier `json:"data,omitempty"`
}

// NewCreateSupplierResponse instantiates a new CreateSupplierResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSupplierResponse() *CreateSupplierResponse {
	this := CreateSupplierResponse{}
	return &this
}

// NewCreateSupplierResponseWithDefaults instantiates a new CreateSupplierResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSupplierResponseWithDefaults() *CreateSupplierResponse {
	this := CreateSupplierResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CreateSupplierResponse) GetData() Supplier {
	if o == nil || isNil(o.Data) {
		var ret Supplier
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSupplierResponse) GetDataOk() (*Supplier, bool) {
	if o == nil || isNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CreateSupplierResponse) HasData() bool {
	if o != nil && !isNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given Supplier and assigns it to the Data field.
func (o *CreateSupplierResponse) SetData(v Supplier) *CreateSupplierResponse {
	o.Data = &v
	return o
}

func (o CreateSupplierResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableCreateSupplierResponse struct {
	value *CreateSupplierResponse
	isSet bool
}

func (v NullableCreateSupplierResponse) Get() *CreateSupplierResponse {
	return v.value
}

func (v *NullableCreateSupplierResponse) Set(val *CreateSupplierResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSupplierResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSupplierResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSupplierResponse(val *CreateSupplierResponse) *NullableCreateSupplierResponse {
	return &NullableCreateSupplierResponse{value: val, isSet: true}
}

func (v NullableCreateSupplierResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSupplierResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


