/*
Fatture in Cloud API v2 - API Reference

Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.

API version: 2.1.8
Contact: info@fattureincloud.it
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package model

import (
	"encoding/json"
)

// checks if the PendingReceivedDocumentExtractedData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PendingReceivedDocumentExtractedData{}

// PendingReceivedDocumentExtractedData struct for PendingReceivedDocumentExtractedData
type PendingReceivedDocumentExtractedData struct {
	Mining *PendingReceivedDocumentExtractedDataMining `json:"mining,omitempty"`
}

// NewPendingReceivedDocumentExtractedData instantiates a new PendingReceivedDocumentExtractedData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPendingReceivedDocumentExtractedData() *PendingReceivedDocumentExtractedData {
	this := PendingReceivedDocumentExtractedData{}
	return &this
}

// NewPendingReceivedDocumentExtractedDataWithDefaults instantiates a new PendingReceivedDocumentExtractedData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPendingReceivedDocumentExtractedDataWithDefaults() *PendingReceivedDocumentExtractedData {
	this := PendingReceivedDocumentExtractedData{}
	return &this
}

// GetMining returns the Mining field value if set, zero value otherwise.
func (o *PendingReceivedDocumentExtractedData) GetMining() PendingReceivedDocumentExtractedDataMining {
	if o == nil || IsNil(o.Mining) {
		var ret PendingReceivedDocumentExtractedDataMining
		return ret
	}
	return *o.Mining
}

// GetMiningOk returns a tuple with the Mining field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PendingReceivedDocumentExtractedData) GetMiningOk() (*PendingReceivedDocumentExtractedDataMining, bool) {
	if o == nil || IsNil(o.Mining) {
		return nil, false
	}
	return o.Mining, true
}

// HasMining returns a boolean if a field has been set.
func (o *PendingReceivedDocumentExtractedData) HasMining() bool {
	if o != nil && !IsNil(o.Mining) {
		return true
	}

	return false
}

// SetMining gets a reference to the given PendingReceivedDocumentExtractedDataMining and assigns it to the Mining field.
func (o *PendingReceivedDocumentExtractedData) SetMining(v PendingReceivedDocumentExtractedDataMining) *PendingReceivedDocumentExtractedData {
	o.Mining = &v
	return o
}

func (o PendingReceivedDocumentExtractedData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PendingReceivedDocumentExtractedData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Mining) {
		toSerialize["mining"] = o.Mining
	}
	return toSerialize, nil
}

type NullablePendingReceivedDocumentExtractedData struct {
	value *PendingReceivedDocumentExtractedData
	isSet bool
}

func (v NullablePendingReceivedDocumentExtractedData) Get() *PendingReceivedDocumentExtractedData {
	return v.value
}

func (v *NullablePendingReceivedDocumentExtractedData) Set(val *PendingReceivedDocumentExtractedData) {
	v.value = val
	v.isSet = true
}

func (v NullablePendingReceivedDocumentExtractedData) IsSet() bool {
	return v.isSet
}

func (v *NullablePendingReceivedDocumentExtractedData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePendingReceivedDocumentExtractedData(val *PendingReceivedDocumentExtractedData) *NullablePendingReceivedDocumentExtractedData {
	return &NullablePendingReceivedDocumentExtractedData{value: val, isSet: true}
}

func (v NullablePendingReceivedDocumentExtractedData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePendingReceivedDocumentExtractedData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

