/*
Fatture in Cloud API v2 - API Reference

Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.

API version: 2.0.23
Contact: info@fattureincloud.it
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package model

import (
	"encoding/json"
)

// GetClientResponse struct for GetClientResponse
type GetClientResponse struct {
	Data *Client `json:"data,omitempty"`
}

// NewGetClientResponse instantiates a new GetClientResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetClientResponse() *GetClientResponse {
	this := GetClientResponse{}
	return &this
}

// NewGetClientResponseWithDefaults instantiates a new GetClientResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetClientResponseWithDefaults() *GetClientResponse {
	this := GetClientResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetClientResponse) GetData() Client {
	if o == nil || isNil(o.Data) {
		var ret Client
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetClientResponse) GetDataOk() (*Client, bool) {
	if o == nil || isNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetClientResponse) HasData() bool {
	if o != nil && !isNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given Client and assigns it to the Data field.
func (o *GetClientResponse) SetData(v Client) *GetClientResponse {
	o.Data = &v
	return o
}

func (o GetClientResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableGetClientResponse struct {
	value *GetClientResponse
	isSet bool
}

func (v NullableGetClientResponse) Get() *GetClientResponse {
	return v.value
}

func (v *NullableGetClientResponse) Set(val *GetClientResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetClientResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetClientResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetClientResponse(val *GetClientResponse) *NullableGetClientResponse {
	return &NullableGetClientResponse{value: val, isSet: true}
}

func (v NullableGetClientResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetClientResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


