/*
Fatture in Cloud API v2 - API Reference

Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.

API version: 2.0.21
Contact: info@fattureincloud.it
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package model

import (
	"encoding/json"
)

// ReceivedDocumentEntity struct for ReceivedDocumentEntity
type ReceivedDocumentEntity struct {
	// Entity unique identifier.
	Id NullableInt32 `json:"id,omitempty"`
	// Entity name.
	Name NullableString `json:"name,omitempty"`
}

// NewReceivedDocumentEntity instantiates a new ReceivedDocumentEntity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReceivedDocumentEntity() *ReceivedDocumentEntity {
	this := ReceivedDocumentEntity{}
	return &this
}

// NewReceivedDocumentEntityWithDefaults instantiates a new ReceivedDocumentEntity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReceivedDocumentEntityWithDefaults() *ReceivedDocumentEntity {
	this := ReceivedDocumentEntity{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReceivedDocumentEntity) GetId() int32 {
	if o == nil || o.Id.Get() == nil {
		var ret int32
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReceivedDocumentEntity) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *ReceivedDocumentEntity) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableInt32 and assigns it to the Id field.
func (o *ReceivedDocumentEntity) SetId(v int32) *ReceivedDocumentEntity {
	o.Id.Set(&v)
	return o
}
// SetIdNil sets the value for Id to be an explicit nil
func (o *ReceivedDocumentEntity) SetIdNil() *ReceivedDocumentEntity {
	o.Id.Set(nil)
	return o
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *ReceivedDocumentEntity) UnsetId() {
	o.Id.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReceivedDocumentEntity) GetName() string {
	if o == nil || o.Name.Get() == nil {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReceivedDocumentEntity) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *ReceivedDocumentEntity) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *ReceivedDocumentEntity) SetName(v string) *ReceivedDocumentEntity {
	o.Name.Set(&v)
	return o
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *ReceivedDocumentEntity) SetNameNil() *ReceivedDocumentEntity {
	o.Name.Set(nil)
	return o
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *ReceivedDocumentEntity) UnsetName() {
	o.Name.Unset()
}

func (o ReceivedDocumentEntity) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableReceivedDocumentEntity struct {
	value *ReceivedDocumentEntity
	isSet bool
}

func (v NullableReceivedDocumentEntity) Get() *ReceivedDocumentEntity {
	return v.value
}

func (v *NullableReceivedDocumentEntity) Set(val *ReceivedDocumentEntity) {
	v.value = val
	v.isSet = true
}

func (v NullableReceivedDocumentEntity) IsSet() bool {
	return v.isSet
}

func (v *NullableReceivedDocumentEntity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReceivedDocumentEntity(val *ReceivedDocumentEntity) *NullableReceivedDocumentEntity {
	return &NullableReceivedDocumentEntity{value: val, isSet: true}
}

func (v NullableReceivedDocumentEntity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReceivedDocumentEntity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


