/*
Fatture in Cloud API v2 - API Reference

Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.

API version: 2.1.5
Contact: info@fattureincloud.it
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package model

import (
	"encoding/json"
)

// checks if the EntityClientPreCreateInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntityClientPreCreateInfo{}

// EntityClientPreCreateInfo struct for EntityClientPreCreateInfo
type EntityClientPreCreateInfo struct {
	// Countries list
	CountriesList []string `json:"countries_list,omitempty"`
	// Entity payment methods list
	PaymentMethodsList []PaymentMethod `json:"payment_methods_list,omitempty"`
	// Entity payment accounts list
	PaymentAccountsList []PaymentAccount `json:"payment_accounts_list,omitempty"`
	// Vat types list
	VatTypesList []VatType `json:"vat_types_list,omitempty"`
	// Entity price lists
	PriceLists []PriceList `json:"price_lists,omitempty"`
	// Entity limit
	Limit NullableFloat32 `json:"limit,omitempty"`
	// Entity usage
	Usage NullableFloat32 `json:"usage,omitempty"`
}

// NewEntityClientPreCreateInfo instantiates a new EntityClientPreCreateInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntityClientPreCreateInfo() *EntityClientPreCreateInfo {
	this := EntityClientPreCreateInfo{}
	return &this
}

// NewEntityClientPreCreateInfoWithDefaults instantiates a new EntityClientPreCreateInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntityClientPreCreateInfoWithDefaults() *EntityClientPreCreateInfo {
	this := EntityClientPreCreateInfo{}
	return &this
}

// GetCountriesList returns the CountriesList field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EntityClientPreCreateInfo) GetCountriesList() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.CountriesList
}

// GetCountriesListOk returns a tuple with the CountriesList field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EntityClientPreCreateInfo) GetCountriesListOk() ([]string, bool) {
	if o == nil || IsNil(o.CountriesList) {
		return nil, false
	}
	return o.CountriesList, true
}

// HasCountriesList returns a boolean if a field has been set.
func (o *EntityClientPreCreateInfo) HasCountriesList() bool {
	if o != nil && !IsNil(o.CountriesList) {
		return true
	}

	return false
}

// SetCountriesList gets a reference to the given []string and assigns it to the CountriesList field.
func (o *EntityClientPreCreateInfo) SetCountriesList(v []string) *EntityClientPreCreateInfo {
	o.CountriesList = v
	return o
}

// GetPaymentMethodsList returns the PaymentMethodsList field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EntityClientPreCreateInfo) GetPaymentMethodsList() []PaymentMethod {
	if o == nil {
		var ret []PaymentMethod
		return ret
	}
	return o.PaymentMethodsList
}

// GetPaymentMethodsListOk returns a tuple with the PaymentMethodsList field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EntityClientPreCreateInfo) GetPaymentMethodsListOk() ([]PaymentMethod, bool) {
	if o == nil || IsNil(o.PaymentMethodsList) {
		return nil, false
	}
	return o.PaymentMethodsList, true
}

// HasPaymentMethodsList returns a boolean if a field has been set.
func (o *EntityClientPreCreateInfo) HasPaymentMethodsList() bool {
	if o != nil && !IsNil(o.PaymentMethodsList) {
		return true
	}

	return false
}

// SetPaymentMethodsList gets a reference to the given []PaymentMethod and assigns it to the PaymentMethodsList field.
func (o *EntityClientPreCreateInfo) SetPaymentMethodsList(v []PaymentMethod) *EntityClientPreCreateInfo {
	o.PaymentMethodsList = v
	return o
}

// GetPaymentAccountsList returns the PaymentAccountsList field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EntityClientPreCreateInfo) GetPaymentAccountsList() []PaymentAccount {
	if o == nil {
		var ret []PaymentAccount
		return ret
	}
	return o.PaymentAccountsList
}

// GetPaymentAccountsListOk returns a tuple with the PaymentAccountsList field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EntityClientPreCreateInfo) GetPaymentAccountsListOk() ([]PaymentAccount, bool) {
	if o == nil || IsNil(o.PaymentAccountsList) {
		return nil, false
	}
	return o.PaymentAccountsList, true
}

// HasPaymentAccountsList returns a boolean if a field has been set.
func (o *EntityClientPreCreateInfo) HasPaymentAccountsList() bool {
	if o != nil && !IsNil(o.PaymentAccountsList) {
		return true
	}

	return false
}

// SetPaymentAccountsList gets a reference to the given []PaymentAccount and assigns it to the PaymentAccountsList field.
func (o *EntityClientPreCreateInfo) SetPaymentAccountsList(v []PaymentAccount) *EntityClientPreCreateInfo {
	o.PaymentAccountsList = v
	return o
}

// GetVatTypesList returns the VatTypesList field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EntityClientPreCreateInfo) GetVatTypesList() []VatType {
	if o == nil {
		var ret []VatType
		return ret
	}
	return o.VatTypesList
}

// GetVatTypesListOk returns a tuple with the VatTypesList field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EntityClientPreCreateInfo) GetVatTypesListOk() ([]VatType, bool) {
	if o == nil || IsNil(o.VatTypesList) {
		return nil, false
	}
	return o.VatTypesList, true
}

// HasVatTypesList returns a boolean if a field has been set.
func (o *EntityClientPreCreateInfo) HasVatTypesList() bool {
	if o != nil && !IsNil(o.VatTypesList) {
		return true
	}

	return false
}

// SetVatTypesList gets a reference to the given []VatType and assigns it to the VatTypesList field.
func (o *EntityClientPreCreateInfo) SetVatTypesList(v []VatType) *EntityClientPreCreateInfo {
	o.VatTypesList = v
	return o
}

// GetPriceLists returns the PriceLists field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EntityClientPreCreateInfo) GetPriceLists() []PriceList {
	if o == nil {
		var ret []PriceList
		return ret
	}
	return o.PriceLists
}

// GetPriceListsOk returns a tuple with the PriceLists field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EntityClientPreCreateInfo) GetPriceListsOk() ([]PriceList, bool) {
	if o == nil || IsNil(o.PriceLists) {
		return nil, false
	}
	return o.PriceLists, true
}

// HasPriceLists returns a boolean if a field has been set.
func (o *EntityClientPreCreateInfo) HasPriceLists() bool {
	if o != nil && !IsNil(o.PriceLists) {
		return true
	}

	return false
}

// SetPriceLists gets a reference to the given []PriceList and assigns it to the PriceLists field.
func (o *EntityClientPreCreateInfo) SetPriceLists(v []PriceList) *EntityClientPreCreateInfo {
	o.PriceLists = v
	return o
}

// GetLimit returns the Limit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EntityClientPreCreateInfo) GetLimit() float32 {
	if o == nil || IsNil(o.Limit.Get()) {
		var ret float32
		return ret
	}
	return *o.Limit.Get()
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EntityClientPreCreateInfo) GetLimitOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Limit.Get(), o.Limit.IsSet()
}

// HasLimit returns a boolean if a field has been set.
func (o *EntityClientPreCreateInfo) HasLimit() bool {
	if o != nil && o.Limit.IsSet() {
		return true
	}

	return false
}

// SetLimit gets a reference to the given NullableFloat32 and assigns it to the Limit field.
func (o *EntityClientPreCreateInfo) SetLimit(v float32) *EntityClientPreCreateInfo {
	o.Limit.Set(&v)
	return o
}
// SetLimitNil sets the value for Limit to be an explicit nil
func (o *EntityClientPreCreateInfo) SetLimitNil() *EntityClientPreCreateInfo {
	o.Limit.Set(nil)
	return o
}

// UnsetLimit ensures that no value is present for Limit, not even an explicit nil
func (o *EntityClientPreCreateInfo) UnsetLimit() {
	o.Limit.Unset()
}

// GetUsage returns the Usage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EntityClientPreCreateInfo) GetUsage() float32 {
	if o == nil || IsNil(o.Usage.Get()) {
		var ret float32
		return ret
	}
	return *o.Usage.Get()
}

// GetUsageOk returns a tuple with the Usage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EntityClientPreCreateInfo) GetUsageOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Usage.Get(), o.Usage.IsSet()
}

// HasUsage returns a boolean if a field has been set.
func (o *EntityClientPreCreateInfo) HasUsage() bool {
	if o != nil && o.Usage.IsSet() {
		return true
	}

	return false
}

// SetUsage gets a reference to the given NullableFloat32 and assigns it to the Usage field.
func (o *EntityClientPreCreateInfo) SetUsage(v float32) *EntityClientPreCreateInfo {
	o.Usage.Set(&v)
	return o
}
// SetUsageNil sets the value for Usage to be an explicit nil
func (o *EntityClientPreCreateInfo) SetUsageNil() *EntityClientPreCreateInfo {
	o.Usage.Set(nil)
	return o
}

// UnsetUsage ensures that no value is present for Usage, not even an explicit nil
func (o *EntityClientPreCreateInfo) UnsetUsage() {
	o.Usage.Unset()
}

func (o EntityClientPreCreateInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntityClientPreCreateInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CountriesList != nil {
		toSerialize["countries_list"] = o.CountriesList
	}
	if o.PaymentMethodsList != nil {
		toSerialize["payment_methods_list"] = o.PaymentMethodsList
	}
	if o.PaymentAccountsList != nil {
		toSerialize["payment_accounts_list"] = o.PaymentAccountsList
	}
	if o.VatTypesList != nil {
		toSerialize["vat_types_list"] = o.VatTypesList
	}
	if o.PriceLists != nil {
		toSerialize["price_lists"] = o.PriceLists
	}
	if o.Limit.IsSet() {
		toSerialize["limit"] = o.Limit.Get()
	}
	if o.Usage.IsSet() {
		toSerialize["usage"] = o.Usage.Get()
	}
	return toSerialize, nil
}

type NullableEntityClientPreCreateInfo struct {
	value *EntityClientPreCreateInfo
	isSet bool
}

func (v NullableEntityClientPreCreateInfo) Get() *EntityClientPreCreateInfo {
	return v.value
}

func (v *NullableEntityClientPreCreateInfo) Set(val *EntityClientPreCreateInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableEntityClientPreCreateInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableEntityClientPreCreateInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntityClientPreCreateInfo(val *EntityClientPreCreateInfo) *NullableEntityClientPreCreateInfo {
	return &NullableEntityClientPreCreateInfo{value: val, isSet: true}
}

func (v NullableEntityClientPreCreateInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntityClientPreCreateInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


