/*
Fatture in Cloud API v2 - API Reference

Testing CashbookApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package fattureincloud

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    fattureincloud "./openapi"
)

func Test_fattureincloud_CashbookApiService(t *testing.T) {

    configuration := fattureincloud.NewConfiguration()
    apiClient := fattureincloud.NewAPIClient(configuration)

    t.Run("Test CashbookApiService CreateCashbookEntry", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var companyId int32

        resp, httpRes, err := apiClient.CashbookApi.CreateCashbookEntry(context.Background(), companyId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test CashbookApiService DeleteCashbookEntry", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var companyId int32
        var documentId string

        resp, httpRes, err := apiClient.CashbookApi.DeleteCashbookEntry(context.Background(), companyId, documentId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test CashbookApiService GetCashbookEntry", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var companyId int32
        var documentId string

        resp, httpRes, err := apiClient.CashbookApi.GetCashbookEntry(context.Background(), companyId, documentId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test CashbookApiService ListCashbookEntries", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var companyId int32

        resp, httpRes, err := apiClient.CashbookApi.ListCashbookEntries(context.Background(), companyId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test CashbookApiService ModifyCashbookEntry", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var companyId int32
        var documentId string

        resp, httpRes, err := apiClient.CashbookApi.ModifyCashbookEntry(context.Background(), companyId, documentId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
