/*
Fatture in Cloud API v2 - API Reference

Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.

API version: 2.0.19
Contact: info@fattureincloud.it
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fattureincloud

import (
	"encoding/json"
)

// UploadReceivedDocumentAttachmentResponse struct for UploadReceivedDocumentAttachmentResponse
type UploadReceivedDocumentAttachmentResponse struct {
	Data *AttachmentData `json:"data,omitempty"`
}

// NewUploadReceivedDocumentAttachmentResponse instantiates a new UploadReceivedDocumentAttachmentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadReceivedDocumentAttachmentResponse() *UploadReceivedDocumentAttachmentResponse {
	this := UploadReceivedDocumentAttachmentResponse{}
	return &this
}

// NewUploadReceivedDocumentAttachmentResponseWithDefaults instantiates a new UploadReceivedDocumentAttachmentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadReceivedDocumentAttachmentResponseWithDefaults() *UploadReceivedDocumentAttachmentResponse {
	this := UploadReceivedDocumentAttachmentResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *UploadReceivedDocumentAttachmentResponse) GetData() AttachmentData {
	if o == nil || o.Data == nil {
		var ret AttachmentData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadReceivedDocumentAttachmentResponse) GetDataOk() (*AttachmentData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *UploadReceivedDocumentAttachmentResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given AttachmentData and assigns it to the Data field.
func (o *UploadReceivedDocumentAttachmentResponse) SetData(v AttachmentData) *UploadReceivedDocumentAttachmentResponse {
	o.Data = &v
	return o
}

func (o UploadReceivedDocumentAttachmentResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableUploadReceivedDocumentAttachmentResponse struct {
	value *UploadReceivedDocumentAttachmentResponse
	isSet bool
}

func (v NullableUploadReceivedDocumentAttachmentResponse) Get() *UploadReceivedDocumentAttachmentResponse {
	return v.value
}

func (v *NullableUploadReceivedDocumentAttachmentResponse) Set(val *UploadReceivedDocumentAttachmentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadReceivedDocumentAttachmentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadReceivedDocumentAttachmentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadReceivedDocumentAttachmentResponse(val *UploadReceivedDocumentAttachmentResponse) *NullableUploadReceivedDocumentAttachmentResponse {
	return &NullableUploadReceivedDocumentAttachmentResponse{value: val, isSet: true}
}

func (v NullableUploadReceivedDocumentAttachmentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadReceivedDocumentAttachmentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


