name: Go SDK Validation

on:
  pull_request:
    branches: [master]

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          ["1.18", "1.19", "1.20", "1.21", "1.22", "1.23", "1.24", "1.25"]

    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
